sudo: false

cache:
  directories:
  - $HOME/.m2

language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./docs/src/main/asciidoc/ghpages.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || mvn --settings .settings.xml clean deploy -nsu'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || mvn --settings .settings.xml clean install -nsu'
env:
  global:
  - GIT_NAME="Spencer Gibb"
  - GIT_EMAIL=sgibb@pivotal.io
  - CI_DEPLOY_USERNAME=sgibb
  - secure: cbst4/p78WIcjFgGV5YJ4x8vTpaMrrDMiVuHi3iprf4vE3KNktod9NW0/C6AB77ik6ndAYHI/qwUpb401DPPGvKf6rMwKtsVelwQu0TPqIhb3aHtOGwYdwQ5sCASkJZv2XvVc1sjjYLL7cXGRn85q1WN8B8JywKU6u9jgt2612o=
